server:
  port: 8081
  servlet:    context-path: /
# for ribbon
eureka:
  instance: 
    hostname: localhost
    appname: eureka-consumer 
    instance-id: consumer1 
    prefer-ip-address: true 
  client:
    #register-with-eureka: true #default true
    service-url: 
      defaultZone: http://eureka3.rui.com:2003/eureka/,http://eureka2.rui.com:2002/eureka/,http://eureka1.rui.com:2001/eureka/
