spring:
  application:
    name: consul-producer1  cloud:    consul:      host: localhost
      port: 8500
      discovery:        service-name: consul-producer #the service which is registered in consul
server:  port: 8501
  
  
